/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TGToken__factory } from "./TGToken__factory";
export { TGTokenFactory__factory } from "./TGTokenFactory__factory";
